version: '3'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.84.0/22
services:
  freqtrade:
    image: freqtradeorg/freqtrade:2025.4
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: BB_RPB_TSL
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "127.0.0.1:8192:8080"
    # # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy BB_RPB_TSL
    # backtesting --strategy EMA3SRSI --config ./user_data/config_backtest.json --timeframe 5m --timerange 20170901- --breakdown month
