version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:2025.10
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./Dockerfile.technical"
    restart: unless-stopped
    container_name: DELTA_NEUTRAL
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    #ports:
    # - "127.0.0.1:8890:8080"
    deploy:
      resources:
        limits:
          cpus: '1.0'      # Limits CPU
          memory: '512M'    # Limit to 512MB of RAM
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json --config /freqtrade/user_data/config-private.json -v
      --strategy DELTA_NEUTRAL

